Repository Ethernal-Tech/blade, pull requests merged in 2024-04, with the labels that each got.

#174 [BLADE-138] Consolidate `TestTxn` to use `TxRelayer`
  e2e-polybft/e2e/acls_test.go
  e2e-polybft/e2e/bridge_test.go
  e2e-polybft/e2e/helpers_test.go
  e2e-polybft/e2e/jsonrpc_test.go
  e2e-polybft/e2e/storage_test.go
  e2e-polybft/framework/test-cluster.go
  txrelayer/txrelayer.go
Labels: enhancement

#188 Add read threads to storagev2 leveldb unit test
  blockchain/storagev2/leveldb/leveldb_perf_test.go
  blockchain/storagev2/leveldb/leveldb_test.go
  blockchain/storagev2/testing.go
  e2e-polybft/e2e/storage_test.go
Labels: enhancement

#190 Secret manager for json RPC TLS
  .github/workflows/e2e-polybft-test.yml
  command/server/config/config.go
  command/server/params.go
  command/server/server.go
  e2e-polybft/e2e/jsonrpc_test.go
  e2e-polybft/framework/test-cluster.go
  e2e-polybft/framework/test-server.go
  jsonrpc/jsonrpc.go
  secrets/local/local.go
  secrets/secrets.go
  server/config.go
  server/server.go
Labels: enhancement

#193 Create TLS certificate with command / load TLS certificate from configuration
  .github/workflows/e2e-polybft-test.yml
  command/secrets/init/params.go
  command/secrets/init/params_test.go
  command/secrets/output/params.go
  command/server/config/config.go
  command/server/params.go
  command/server/server.go
  e2e-polybft/e2e/jsonrpc_test.go
  e2e-polybft/framework/test-cluster.go
  e2e-polybft/framework/test-server.go
  jsonrpc/jsonrpc.go
  secrets/helper/helper.go
  secrets/local/local.go
  secrets/local/local_test.go
  secrets/secrets.go
  server/config.go
  server/server.go
Labels: feature

#194 Load test runner implementation
  command/bridge/fund/fund.go
  command/loadtest/load_test_run.go
  command/loadtest/params.go
  command/root/root.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/contractsapi/init.go
  consensus/polybft/contractsapi/test-contracts/ZexCoinERC20.json
  consensus/polybft/contractsapi/test-contracts/ZexNFT.json
  consensus/polybft/fsm.go
  consensus/polybft/polybft.go
  consensus/polybft/stake_manager_test.go
  consensus/polybft/stale_sequence_check.go
  go.mod
  go.sum
  jsonrpc/client.go
  loadtest/runner/base_load_test_runner.go
  loadtest/runner/eoa_runner.go
  loadtest/runner/erc20_runner.go
  loadtest/runner/erc721_runner.go
  loadtest/runner/load_test_runner.go
  loadtest/runner/load_test_runner_test.go
  scripts/cluster
  txpool/txpool.go
  txpool/txpool_test.go
  txrelayer/txrelayer.go
Labels: feature

#196 Fix for ERC20 load test freeze
  consensus/polybft/stale_sequence_check.go
Labels: bug-fix

#197 Sending txs in batches in Load Test Tool
  command/loadtest/load_test_run.go
  command/loadtest/params.go
  loadtest/runner/base_load_test_runner.go
  loadtest/runner/eoa_runner.go
  loadtest/runner/erc20_runner.go
  loadtest/runner/erc721_runner.go
  loadtest/runner/load_test_runner.go
  loadtest/runner/transaction_batch_sender.go
Labels: feature

#198 `ResetWithHeaders` optimization
  consensus/dev/dev.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/fsm.go
  consensus/polybft/mocks_test.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: performance-improvements

#199 Lower logging on dispatcher, jsonrpc and txpool
  consensus/polybft/block_builder.go
  jsonrpc/dispatcher.go
  jsonrpc/jsonrpc.go
  txpool/txpool.go
Labels: technical-debt

#200 libp2p pubsub max message size set to 4 MB
  network/server.go
Labels: bug-fix

#203 Load test with mixed transactions
  loadtest/runner/base_load_test_runner.go
  loadtest/runner/load_test_runner.go
  loadtest/runner/mixed_tx_runner.go
  state/executor.go
Labels: feature, tests

#173 E2E tests for `eth_createAccessList` and `eth_getBlockReceipts`
  e2e-polybft/e2e/jsonrpc_test.go
  jsonrpc/client.go
  jsonrpc/helper.go
  jsonrpc/types.go
  txrelayer/txrelayer.go
Labels: tests

#208 Include consensus halt fix
  consensus/polybft/consensus_runtime.go
  consensus/polybft/polybft.go
  consensus/polybft/stale_sequence_check.go
  go.mod
  go.sum
Labels: bug-fix

#209 `EIP1559` token burning fix
  consensus/polybft/polybft.go
  e2e-polybft/e2e/consensus_test.go
  server/builtin.go
  server/server.go
  state/executor.go
Labels: bug-fix

#210 Fix for txpool loosing txs
  consensus/dev/dev.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/mocks_test.go
  txpool/account.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: bug-fix

#213 SequenceCancelled backend callback
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  go.mod
  go.sum
Labels: enhancement, bug-fix
