Repository Ethernal-Tech/blade, pull requests merged in 2024-02, with the labels that each got.

#86 Berlin fixes
  crypto/txsigner.go
  state/executor.go
  state/runtime/access_list.go
  state/runtime/evm/evm.go
  state/runtime/evm/instructions.go
  state/runtime/evm/instructions_test.go
  state/runtime/evm/state.go
  state/runtime/journal.go
  state/runtime/runtime.go
  tests/state_test_util.go
Labels: bug-fix

#111 London test fixes
  consensus/polybft/blockchain_wrapper.go
  consensus/polybft/contracts_initializer.go
  consensus/polybft/sc_integration_test.go
  consensus/polybft/system_state_test.go
  e2e-polybft/e2e/consensus_test.go
  helper/predeployment/predeployment.go
  state/executor.go
  state/executor_test.go
  state/runtime/evm/dispatch_table.go
  state/runtime/evm/evm_fuzz_test.go
  state/runtime/evm/evm_test.go
  state/runtime/evm/instructions.go
  state/runtime/evm/instructions_test.go
  state/runtime/journal.go
  state/runtime/precompiled/base.go
  state/runtime/precompiled/native_transfer_test.go
  state/runtime/runtime.go
  state/transition_test.go
  state/txn.go
  tests/state_test_util.go
Labels: bug-fix

#123 New UTs for `buildroot` package
  types/buildroot/buildroot_fast_test.go
  types/buildroot/buildroot_test.go
Labels: technical-debt

#124 Pooling of big.Int instances in the EVM
  helper/common/common.go
  helper/common/common_test.go
  state/runtime/evm/instructions_test.go
  state/runtime/evm/state.go
Labels: performance-improvements

#115 [BLADE-97] Refactor tx signer
  crypto/crypto.go
  crypto/txsigner.go
  crypto/txsigner_berlin.go
  crypto/txsigner_eip155.go
  crypto/txsigner_eip155_test.go
  crypto/txsigner_frontier.go
  crypto/txsigner_homestead.go
  crypto/txsigner_london.go
  crypto/txsigner_london_berlin.go
  crypto/txsigner_london_test.go
  e2e/txpool_test.go
  gasprice/gasprice_test.go
  helper/tests/testing.go
  jsonrpc/testsuite/block-with-txn-full.json
  server/server.go
  txpool/txpool.go
  txpool/txpool_test.go
  types/access_list_tx.go
  types/dynamic_fee_tx.go
  types/legacy_tx.go
  types/state_tx.go
Labels: technical-debt

#127 [BLADE-70] Fix blade version CLI command
  Makefile
Labels: technical-debt
