Repository Ethernal-Tech/blade, pull requests merged in 2024-10, with the labels that each got.

#400 replace armon dependency with hashicorp
  consensus/polybft/consensus_metrics.go
  consensus/polybft/fsm.go
  consensus/polybft/stats.go
  go.mod
  go.sum
  jsonrpc/dispatcher.go
  network/gossip.go
  network/server.go
  network/server_identity.go
  server/server_metrics.go
  syncer/client.go
  syncer/service.go
  syncer/syncer.go
  txpool/slot_gauge.go
  txpool/txpool.go
Labels: dependencies

#404 Reward distribution fix
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/fsm.go
  consensus/polybft/governance_manager.go
Labels: bug-fix

#410 Introduction of Oracles
  .mockery.yml
  Makefile
  consensus/polybft/bridge/bridge.go
  consensus/polybft/bridge/bridge_manager.go
  consensus/polybft/bridge/bridge_manager_test.go
  consensus/polybft/bridge/bridge_test.go
  consensus/polybft/bridge/bridgemanager.mock.generated.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/epoch/epoch_manager.go
  consensus/polybft/epoch/epoch_manager_test.go
  consensus/polybft/fsm.go
  consensus/polybft/fsm_test.go
  consensus/polybft/governance/governance_manager.go
  consensus/polybft/governance/governance_manager_test.go
  consensus/polybft/helpers/runtime_helpers.go
  consensus/polybft/oracle/handlers.go
  consensus/polybft/oracle/oracle.go
  consensus/polybft/polybft.go
  consensus/polybft/polybft_test.go
  consensus/polybft/proposer/proposer_calculator.go
  consensus/polybft/sc_integration_test.go
  consensus/polybft/stake/stake_manager.go
  consensus/polybft/stake/stake_manager_fuzz_test.go
  consensus/polybft/stake/stake_manager_test.go
  consensus/polybft/types/extra_test.go
  consensus/polybft/types/mocks.go
  consensus/polybft/types/polybft.mock.generated.go
Labels: feature

#412 feat: introduce safe and finalized as block number filters
  e2e-polybft/e2e/jsonrpc_test.go
  jsonrpc/codec.go
  jsonrpc/codec_test.go
  jsonrpc/helper.go
  jsonrpc/helper_test.go
Labels: feature
