Repository Ethernal-Tech/blade, pull requests merged in 2024-06, with the labels that each got.

#279 Throttling UT improvement
  jsonrpc/throttling_test.go
Labels: tests

#245 Adding check inside EVM loop for errors to avoid executing contract w…
  state/runtime/evm/state.go
  state/runtime/evm/state_test.go
Labels: bug-fix

#281 e2e register validator fix
  e2e-polybft/e2e/consensus_test.go
Labels: tests

#275 Optimized opMLoad to avoid unnecessary allocations.
  state/runtime/evm/instructions.go
Labels: enhancement

#283 Test improvements
  e2e-polybft/framework/test-server.go
  jsonrpc/throttling_test.go
Labels: tests

#276 Removing unnecessary sp field from OptimizedStack.
  state/runtime/evm/evm_test.go
  state/runtime/evm/instructions.go
  state/runtime/evm/instructions_test.go
  state/runtime/evm/optimized_stack.go
  state/runtime/evm/optimized_stack_benchmark_test.go
  state/runtime/evm/optimized_stack_test.go
  state/runtime/evm/state.go
  state/runtime/runtime.go
Labels: enhancement

#284 Display dynamic fee transactions in block explorers
  jsonrpc/eth_blockchain_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/helper.go
  jsonrpc/txpool_endpoint.go
  jsonrpc/txpool_endpoint_test.go
  jsonrpc/types.go
  jsonrpc/types_test.go
Labels: bug-fix

#291 fix path account management
  accounts/keystore/keystore.go
  server/server.go
Labels: bug-fix

#292 Rename go-ibft Message to IbftMessage
  consensus/polybft/consensus_runtime.go
  consensus/polybft/consensus_runtime_test.go
  consensus/polybft/fsm.go
  consensus/polybft/transport.go
  consensus/polybft/wallet/key.go
  consensus/polybft/wallet/key_test.go
  go.mod
  go.sum
  network/gossip_test.go
Labels: feature, tests

#294 Implementation of `eth_sendTransaction`
  e2e-polybft/e2e/jsonrpc_test.go
  helper/common/common.go
  jsonrpc/eth_endpoint.go
  jsonrpc/types.go
Labels: feature

#295 Implementation of `eth_sign`
  e2e-polybft/e2e/jsonrpc_test.go
  jsonrpc/client.go
  jsonrpc/eth_endpoint.go
Labels: feature

#296 TestE2E_Bridge_NonMintableERC20Token_WithPremine fix
  e2e-polybft/e2e/bridge_test.go
Labels: tests
