Repository Ethernal-Tech/blade, pull requests merged in 2024-03, with the labels that each got.

#129 Load tests improvement
  loadtest/helpers/init.js
  loadtest/scenarios/multiple_EOA.js
  loadtest/scenarios/multiple_ERC20.js
  scripts/cluster
  server/server.go
  txpool/txpool.go
  txpool/txpool_test.go
Labels: enhancement

#152 `eth_estimateGas` fix
  jsonrpc/eth_endpoint.go
Labels: bug-fix

#154 jsonrpc with https
  command/server/config/config.go
  command/server/params.go
  command/server/server.go
  e2e-polybft/e2e/jsonrpc_test.go
  e2e-polybft/framework/test-cluster.go
  e2e-polybft/framework/test-server.go
  jsonrpc/jsonrpc.go
  server/config.go
  server/server.go
Labels: feature

#158 TLS certificate on CI
  .github/workflows/e2e-polybft-test.yml
  e2e-polybft/e2e/jsonrpc_test.go
  e2e-polybft/framework/test-server.go
  jsonrpc/jsonrpc.go
Labels: feature

#160 New 'Ethereum JSONRPC' client implementation
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/consensus_runtime.go
  consensus/polybft/governance_manager_test.go
  consensus/polybft/helpers_test.go
  consensus/polybft/polybft.go
  consensus/polybft/sc_integration_test.go
  consensus/polybft/stake_manager.go
  consensus/polybft/stake_manager_fuzz_test.go
  consensus/polybft/state_event_getter.go
  consensus/polybft/state_store_exit.go
  consensus/polybft/state_store_state_sync.go
  consensus/polybft/state_sync_commitment.go
  consensus/polybft/state_sync_relayer.go
  consensus/polybft/stats.go
  e2e-polybft/e2e/helpers_test.go
  e2e-polybft/e2e/jsonrpc_test.go
  go.mod
  jsonrpc/client.go
  jsonrpc/codec.go
  jsonrpc/dispatcher.go
  jsonrpc/eth_endpoint.go
  jsonrpc/eth_endpoint_test.go
  jsonrpc/jsonrpc.go
  jsonrpc/types.go
  state/runtime/precompiled/console.go
  types/access_list_tx.go
  types/base_tx.go
  types/dynamic_fee_tx.go
  types/json_unmarshal.go
  types/legacy_tx.go
  types/state_tx.go
  types/transaction.go
Labels: feature

#164 Validator Snapshot bug fix
  consensus/polybft/state_store_epoch.go
  consensus/polybft/state_store_epoch_test.go
  consensus/polybft/validators_snapshot.go
Labels: bug-fix

#126 LevelDB with 2 databases
  blockchain/blockchain.go
  blockchain/blockchain_test.go
  blockchain/storage/leveldb/leveldb_perf_test.go
  blockchain/storagev2/leveldb/batch.go
  blockchain/storagev2/leveldb/leveldb.go
  blockchain/storagev2/leveldb/leveldb_perf_test.go
  blockchain/storagev2/leveldb/leveldb_test.go
  blockchain/storagev2/mdbx/batch.go
  blockchain/storagev2/mdbx/mdbx.go
  blockchain/storagev2/mdbx/mdbx_perf_test.go
  blockchain/storagev2/mdbx/mdbx_test.go
  blockchain/storagev2/memory/batch.go
  blockchain/storagev2/memory/memory.go
  blockchain/storagev2/memory/memory_test.go
  blockchain/storagev2/storage.go
  blockchain/storagev2/storage_read.go
  blockchain/storagev2/storage_write.go
  blockchain/storagev2/testing.go
  blockchain/storagev2/testing_perf.go
  blockchain/storagev2/utils.go
  blockchain/testing.go
  command/regenesis/test_on_history.go
  e2e-polybft/e2e/storage_test.go
  go.mod
  go.sum
  jsonrpc/debug_endpoint.go
  jsonrpc/debug_endpoint_test.go
  jsonrpc/eth_blockchain_test.go
  jsonrpc/eth_endpoint.go
  jsonrpc/helper.go
  jsonrpc/helper_test.go
  server/server.go
Labels: feature, performance-improvements

#168 2nd leveldb database instance removal
  blockchain/storagev2/leveldb/leveldb.go
  blockchain/storagev2/storage.go
Labels: feature

#165 Usage of new `EthClient`
  command/bridge/deploy/deploy.go
  command/bridge/deploy/deploy_test.go
  command/bridge/exit/exit.go
  command/regenesis/get_root.go
  command/validator/registration/register_validator.go
  consensus/polybft/checkpoint_manager_test.go
  consensus/polybft/stake_manager_test.go
  e2e-polybft/e2e/acls_test.go
  e2e-polybft/e2e/bridge_test.go
  e2e-polybft/e2e/burn_contract_test.go
  e2e-polybft/e2e/consensus_test.go
  e2e-polybft/e2e/governance_test.go
  e2e-polybft/e2e/helpers_test.go
  e2e-polybft/e2e/jsonrpc_test.go
  e2e-polybft/e2e/migration_test.go
  e2e-polybft/e2e/storage_test.go
  e2e-polybft/e2e/txpool_test.go
  e2e-polybft/framework/test-cluster.go
  e2e-polybft/framework/test-server.go
  e2e-polybft/property/property_test.go
  e2e/framework/helper.go
  e2e/framework/testserver.go
  e2e/transaction_test.go
  e2e/txpool_test.go
  gasprice/feehistory_test.go
  gasprice/gasprice_test.go
  helper/common/common.go
  helper/tests/testing.go
  jsonrpc/client.go
  jsonrpc/jsonrpc_test.go
  jsonrpc/types.go
  network/e2e_testing.go
  txrelayer/txrelayer.go
  types/access_list_tx.go
  types/base_tx.go
  types/dynamic_fee_tx.go
  types/json_marshal.go
  types/json_marshalling_util.go
  types/json_unmarshal.go
  types/legacy_tx.go
  types/state_tx.go
  types/transaction.go
Labels: feature
