Repository Ethernal-Tech/blade, pull requests merged in 2024-05, with the labels that each got.

#215 Updated `polybft` package `README.md`
  consensus/polybft/README.md
Labels: documentation

#228 Bump libp2p dependencies
  go.mod
  go.sum
Labels: dependencies

#229 Start ogmios with cluster
  .github/workflows/e2e-polybft-test.yml
  .github/workflows/unit-test.yml
  .gitignore
  Makefile
  e2e-polybft/cardanofw/files/configuration.yaml
  e2e-polybft/cardanofw/test-apex-bridge.go
  e2e-polybft/cardanofw/test-cardano-cluster.go
  e2e-polybft/cardanofw/test-cardano-server.go
  e2e-polybft/cardanofw/test-cardano-stats.go
  e2e-polybft/cardanofw/test-cardano-tx.go
  e2e-polybft/cardanofw/test-cardano-utils.go
  e2e-polybft/cardanofw/test-cardano-validator.go
  e2e-polybft/cardanofw/test-ogmios-server.go
  e2e-polybft/e2e/cardano_test.go
  go.mod
  go.sum
Labels: bug-fix

#230 Validator snapshot calculation optimization
  consensus/polybft/validator/validator_metadata.go
  consensus/polybft/validators_snapshot.go
  consensus/polybft/validators_snapshot_test.go
Labels: performance-improvements

#235 Commitment deadlock fix
  consensus/polybft/state_sync_manager.go
  e2e-polybft/e2e/bridge_test.go
Labels: bug-fix, tests

#238 e2e fixes
  e2e-polybft/e2e/bridge_test.go
Labels: tests

#237 Block Time change through governance `e2e` test
  consensus/polybft/contractsapi/bindings-gen/main.go
  consensus/polybft/contractsapi/contractsapi.go
  e2e-polybft/e2e/governance_test.go
Labels: tests

#241 UT improvements
  jsonrpc/throttling_test.go
  network/server_test.go
  txpool/txpool_test.go
Labels: tests

#244 Modify throttling UT times
  jsonrpc/throttling_test.go
  network/gossip_test.go
Labels: tests

#240 Sanity check tests
  command/genesis/params.go
  command/genesis/polybft_params.go
  command/genesis/utils.go
  command/loadtest/load_test_run.go
  command/loadtest/params.go
  command/root/root.go
  command/sanitycheck/params.go
  command/sanitycheck/sanity_check.go
  loadtest/sanitycheck/base_sanity_check.go
  loadtest/sanitycheck/sanity_check_register_validator.go
  loadtest/sanitycheck/sanity_check_runner.go
  loadtest/sanitycheck/sanity_check_stake.go
  loadtest/sanitycheck/sanity_check_test.go
  loadtest/sanitycheck/sanity_check_unstake.go
  loadtest/sanitycheck/sanity_check_unstake_all.go
  loadtest/sanitycheck/sanity_check_withdraw_rewards.go
  network/server_test.go
  scripts/cluster
  txpool/txpool_test.go
Labels: feature, tests

#251 Remove old storage
  blockchain/storage/batch_writer.go
  blockchain/storage/keyvalue.go
  blockchain/storage/leveldb/batch.go
  blockchain/storage/leveldb/leveldb.go
  blockchain/storage/leveldb/leveldb_perf_test.go
  blockchain/storage/leveldb/leveldb_test.go
  blockchain/storage/memory/batch.go
  blockchain/storage/memory/memory.go
  blockchain/storage/memory/memory_test.go
  blockchain/storage/storage.go
  blockchain/storage/testing.go
  blockchain/storage/utils.go
  network/slots_test.go
Labels: technical-debt, tests

#170 Introducing OptimizedStack based on uint256 integers
  e2e-polybft/e2e/jsonrpc_test.go
  e2e-polybft/e2e/storage_test.go
  e2e-polybft/e2e/txpool_test.go
  go.mod
  go.sum
  state/runtime/evm/dispatch_table_test.go
  state/runtime/evm/evm_test.go
  state/runtime/evm/instructions.go
  state/runtime/evm/instructions_benchmark_test.go
  state/runtime/evm/instructions_test.go
  state/runtime/evm/optimized_stack.go
  state/runtime/evm/optimized_stack_benchmark_test.go
  state/runtime/evm/optimized_stack_test.go
  state/runtime/evm/state.go
  state/runtime/evm/state_test.go
  state/runtime/runtime.go
  state/runtime/tracer/calltracer/call_tracer.go
  state/runtime/tracer/structtracer/tracer.go
  state/runtime/tracer/structtracer/tracer_test.go
  state/runtime/tracer/types.go
Labels: enhancement, feature, performance-improvements

#254 Future epoch commitment fix
  consensus/polybft/state_sync_manager.go
  consensus/polybft/state_sync_manager_test.go
Labels: enhancement

#255 `Syncer` stuck fix
  consensus/polybft/mocks_test.go
  consensus/polybft/polybft.go
  syncer/syncer.go
  syncer/types.go
Labels: bug-fix

#257 TestE2E_Consensus_RegisterValidator fix
  consensus/polybft/system_state.go
  e2e-polybft/e2e/consensus_test.go
Labels: tests

#258 Increase gossip message size in `CI`
  .github/workflows/nightly.yml
  consensus/polybft/polybft.go
Labels: bug-fix
